name: "My action"
description: "Test my action"

inputs: #definimos parámetros
  message: "The message to pint"
  required: true
  default: "Hola"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "${{inputs.message}}" #llamamos al parametro
      shell: bash