name: Test

on: [push]

jobs:
  test-build:
    runs-on:

    steps:
      - name: Checkout code
        run: actions/checkout@v2

      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Lizette"
